# Generated by Django 4.2.7 on 2024-01-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default="B", max_length=1)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["code", "name"],
            },
        ),
        migrations.AddField(
            model_name="node",
            name="node_standard",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="path_app.nodestandard",
            ),
        ),
    ]
