# Generated by Django 4.2.7 on 2024-01-23 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0002_alter_currentversion_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentversion",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="path_app.version",
            ),
        ),
    ]
