# Generated by Django 4.2.7 on 2024-01-21 06:38

from django.db import migrations, models
import django.db.models.deletion
import path_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0002_nodestandard_node_node_standard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="node_standard",
            field=models.ForeignKey(
                blank=True,
                default=path_app.models.Node.get_default_node_standard,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="path_app.nodestandard",
            ),
        ),
    ]
