# Generated by Django 4.2.7 on 2024-01-21 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0003_alter_node_node_standard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="node_standard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="path_app.nodestandard",
            ),
        ),
    ]
