# Generated by Django 4.2.7 on 2024-01-25 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0003_alter_currentversion_version"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="node",
            unique_together={("node_text", "category", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="nodestandard",
            unique_together={("code", "name")},
        ),
        migrations.CreateModel(
            name="LinkStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_node",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_node",
                        to="path_app.nodestandard",
                    ),
                ),
                (
                    "to_node",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_node",
                        to="path_app.nodestandard",
                    ),
                ),
            ],
            options={
                "ordering": ["from_node", "to_node"],
                "unique_together": {("from_node", "to_node")},
            },
        ),
    ]
