# Generated by Django 4.2.7 on 2024-01-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0004_alter_node_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="node",
            unique_together={("node_code", "category", "version")},
        ),
    ]
