# Generated by Django 4.2.7 on 2024-01-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0005_alter_node_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="node",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="node",
            name="temp",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="node",
            unique_together={("node_code", "category", "version", "temp")},
        ),
    ]
