# Generated by Django 4.2.7 on 2024-01-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0007_alter_node_unique_together_node_unique_node_code"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                fields=("node_text", "category", "version", "temp"),
                name="unique_node_text",
            ),
        ),
    ]
