# Generated by Django 4.2.7 on 2024-01-26 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0008_node_unique_node_text"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="node",
            name="unique_node_text",
        ),
    ]
