# Generated by Django 4.2.7 on 2024-01-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0009_remove_node_unique_node_text"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                fields=("node_text", "category", "version", "temp"),
                name="unique_node_text",
            ),
        ),
    ]
