# Generated by Django 4.2.7 on 2024-01-28 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0011_remove_node_unique_node_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="linkstandard",
            options={"ordering": ["from_node_standard", "to_node_standard"]},
        ),
        migrations.RenameField(
            model_name="linkstandard",
            old_name="from_node",
            new_name="from_node_standard",
        ),
        migrations.RenameField(
            model_name="linkstandard",
            old_name="to_node",
            new_name="to_node_standard",
        ),
        migrations.AlterUniqueTogether(
            name="linkstandard",
            unique_together={("from_node_standard", "to_node_standard")},
        ),
    ]
