# Generated by Django 4.2.7 on 2024-01-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0012_alter_linkstandard_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkstandard",
            name="remove",
            field=models.BooleanField(default=False),
        ),
    ]
