# Generated by Django 4.2.7 on 2024-02-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0013_linkstandard_remove"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkparam",
            name="Edit_standard_links",
            field=models.BooleanField(default=False),
        ),
    ]
