# Generated by Django 4.2.7 on 2024-02-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0014_networkparam_edit_standard_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkstandard",
            name="date_added",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="linkstandard",
            name="user_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="linkstandard",
            name="version_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
