# Generated by Django 4.2.7 on 2024-02-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0015_linkstandard_date_added_linkstandard_user_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=1)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["code", "name"],
                "unique_together": {("code", "name")},
            },
        ),
    ]
