# Generated by Django 4.2.7 on 2024-02-04 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0017_currentversion_from_selected_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentversion",
            name="from_selected",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_selected",
                to="path_app.category",
            ),
        ),
        migrations.AlterField(
            model_name="currentversion",
            name="to_selected",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_selected",
                to="path_app.category",
            ),
        ),
    ]
