# Generated by Django 4.2.7 on 2024-02-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0018_alter_currentversion_from_selected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ganttparam",
            name="Show_combined",
            field=models.BooleanField(default=False),
        ),
    ]
