# Generated by Django 4.2.7 on 2024-02-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0019_ganttparam_show_combined"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="short_name",
            field=models.CharField(default="default", max_length=50),
        ),
    ]
