# Generated by Django 4.2.7 on 2024-02-11 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0020_version_short_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiParam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Plot_width",
                    models.IntegerField(blank=True, default=1000, null=True),
                ),
                (
                    "Plot_height",
                    models.IntegerField(blank=True, default=1000, null=True),
                ),
                (
                    "Plot_padding",
                    models.IntegerField(blank=True, default=10, null=True),
                ),
                (
                    "Internal_padding",
                    models.IntegerField(blank=True, default=10, null=True),
                ),
                ("Legend_limit", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "Legend_x_spacing",
                    models.IntegerField(blank=True, default=140, null=True),
                ),
                (
                    "Legend_y_spacing",
                    models.IntegerField(blank=True, default=30, null=True),
                ),
                (
                    "Legend_box_pad",
                    models.IntegerField(blank=True, default=10, null=True),
                ),
                ("Top_margin", models.IntegerField(blank=True, default=50, null=True)),
                (
                    "Right_margin",
                    models.IntegerField(blank=True, default=50, null=True),
                ),
                (
                    "Y_axis_space",
                    models.IntegerField(blank=True, default=250, null=True),
                ),
                (
                    "X_axis_space",
                    models.IntegerField(blank=True, default=50, null=True),
                ),
                (
                    "Pixels_per_row",
                    models.IntegerField(blank=True, default=16, null=True),
                ),
                ("Bar_padding", models.IntegerField(blank=True, default=3, null=True)),
                ("Tick_length", models.IntegerField(blank=True, default=5, null=True)),
                (
                    "JPG_output_resolution",
                    models.IntegerField(blank=True, default=4, null=True),
                ),
                ("Enabled_only", models.BooleanField(default=True)),
                (
                    "copied_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="path_app.multiparam",
                    ),
                ),
                (
                    "version",
                    models.OneToOneField(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="path_app.version",
                    ),
                ),
            ],
        ),
    ]
