# Generated by Django 4.2.7 on 2024-02-11 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("path_app", "0022_remove_multiparam_jpg_output_resolution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="multiparam",
            name="version",
        ),
        migrations.AddField(
            model_name="multiparam",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
