# Generated by Django 4.2.7 on 2024-02-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("path_app", "0023_remove_multiparam_version_multiparam_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiparam",
            name="Count_order",
            field=models.BooleanField(default=False),
        ),
    ]
